name: lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: node-10-browsers
        uses: aquariuslt/node-browsers-github-actions@master
      - name: Install and prettier
        run: |
          yarn run install
          yarn run prettier --write src/**/*.{ts,tsx}
